### ISSUE TITLE
Interface language

### ISSUE THREAD

**Issue by lue** [akaurov/biostar-central#3]
Remove all hard-coded interface text from templates.

**Comment by cyc60** [comment]
done, https://github.com/akaurov/biostar-central/commit/ccccdec926953ebcee0c78e55873aa5f3517a439.
Russian translation is stored in https://github.com/akaurov/biostar-central/blob/master/biostar/locale/ru/LC_MESSAGES/django.po file.
Then you update translation, must execute `run manage.py compilemessages  -l ru`
